Developmentbranch
bgsu-pal/paclab-www pull request #1
Opened 2018-10-11 14:36 UTC by rebbrunner

Add current website to repo -
.gitignore was based off linked article as well as several posts in stackexchange.
Database and env file are in ignore, will have to be created on each unit.
Decoupled SECRET_KEY, DEBUG, ALLOWED_HOSTS, and DATABASES.  No testing done on if this setup works on server yet.

2018-10-11 15:57 UTC, psybers requested changes
We arent ignoring media/ ?

2018-10-11 15:57 UTC, psybers commented on .gitignore
> +hs_err_pid*
all the above ignores are for Java projects - we can remove these

2018-10-11 16:00 UTC, psybers commented
static/website/people was removed on the server - dont commit these

2018-10-11 16:01 UTC, psybers commented
remove default parent/child models and all associated data for them

2018-10-11 16:02 UTC, psybers commented
Your commits are still not linking properly to your GH user.

2018-10-11 17:51 UTC, rebbrunner commented
I removed the given lines from .gitignore and added media/.
I removed the people subdirectory from static
I removed the default parent/child and ran manage.py makemigrations and migrate.
I don't know what the problem is with my GH account I checked my local and global commit and my name and email are displaying. :S

2018-10-11 19:07 UTC, psybers commented
The media/ files are still in the commit.

2018-10-11 19:08 UTC, psybers commented
Since we are pushing the 'first iteration' of this website, there probably doesnt need to be a migrations folder/files.

2018-10-15 00:40 UTC, rebbrunner commented
I unstaged all changes and re-added them then committed.
Updated user.name to Rebecca Brunner and email to brunner@bgsu.edu

2018-10-15 00:44 UTC, rebbrunner commented
Trying to figure out why my account is not linking correctly.  Will re-commit asap.

2018-10-15 00:53 UTC, rebbrunner commented
Removed migrations folder for initial commit

2018-10-15 00:56 UTC, rebbrunner commented
Also, on a side note, I have fixed the people pages bug, added the given groups (could not determine how to automatically generate groups atm), added sorting by groups, template tags for sorting via groups, and a context processor to store constants to use in templates.  All these changes are stored in my other repository and I will migrate them over to the main repo/server once we have the initial backup on GitHub setup.

2018-10-15 00:58 UTC, psybers commented
I'm still unsure if we should be pushing the static files. Read up a bit.

https://docs.djangoproject.com/en/2.1/howto/static-files/
https://docs.djangoproject.com/en/2.1/howto/static-files/deployment/
https://docs.djangoproject.com/en/2.1/ref/contrib/staticfiles/#django-admin-collectstatic

2018-10-15 01:05 UTC, rebbrunner commented
Ah okay, so typically in production static files can be stored in another location and are transferred over to the server's static folder via command/service.  I will add the static files to the .gitignore.  Also, I apologize for how long this is taking.  I am completely new to deploying apps in a production environment and am learning as we go!

2018-10-15 01:08 UTC, rebbrunner commented
Static files added to .gitignore.

2018-10-15 01:24 UTC, psybers commented
We have some custom static files though - how do we handle those?  Probably we dont want to just ignore them.

2018-10-15 15:04 UTC, psybers approved these changes

2018-10-15 15:05 UTC, merged