Password fix
bgsu-pal/paclab-www pull request #44
Opened 2019-02-20 18:28 UTC by rebbrunner

- Adds better password validation
- Add password change option to dropdown menu

2019-02-20 18:35 UTC, rebbrunner commented
fixes #35 fixes #39

2019-02-20 18:54 UTC, psybers requested changes

2019-02-20 18:54 UTC, psybers commented on website/templates/website/layout.html
> +                            <li><a href="{% url 'website:project_selection' %}">Project Selection</a></li>
this is below now - remove this line

2019-02-20 18:54 UTC, psybers commented on website/templates/website/layout.html
> +                            <li><a href="{% url 'website:password_change' %}">Change Password</a></li>
lets move change password under 'your profile'

2019-02-20 18:54 UTC, psybers commented on website/templates/website/password_change.html
> +{% block title %}Edit Password{% endblock %}
'Change password'

2019-02-20 18:54 UTC, psybers commented on website/views.py
> +            form.save()
so after a register we no longer log them in?

2019-02-22 21:47 UTC, psybers approved these changes

2019-02-22 21:47 UTC, merged